#[derive(Debug, serde::Deserialize)]
pub struct ScryfallCard {
    pub id: Option<String>,
    pub oracle_id: Option<String>,
    pub name: Option<String>,
    pub printed_name: Option<String>,
    pub lang: Option<String>,
    pub layout: Option<String>,
    pub mana_cost: Option<String>,
    pub cmc: Option<f64>,
    pub type_line: Option<String>,
    pub printed_type_line: Option<String>,
    pub oracle_text: Option<String>,
    pub power: Option<String>,
    pub toughness: Option<String>,
    pub colors: Option<Vec<String>>,
    pub color_identity: Option<Vec<String>>,
    pub keywords: Option<Vec<String>>,
    pub set: Option<String>,
    pub set_name: Option<String>,
    pub collector_number: Option<String>,
    pub rarity: Option<String>,
}
